name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: Adityasah2004
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg
